### ISSUE TITLE
feat: More options for pulling down frontends

### ISSUE THREAD

**Issue by MrYuion** [PlaceOS/frontend-loader#25]
Currently we are pulling frontends down from repository branches but the build artifacts are starting to bloat the git history of those repositories.
To address this issue I'd like to have more options for pulling down repositories down from the server.
Possible methods could include:

- Linking to Github releases.
- Linking to URLs on the web.

For auto-updating we could either hash files to check for changes or possible get change information from an API associated with the data source.

**Comment by MrYuion** [comment]
@caspiano @w-le @stakach @kimburgess

**Comment by kimburgess** [comment]
Having the ability to pull and unpack a tar feels like a neat solution here. This would provide the ability to pull these from arbitrary sources, or if using GitHub, UX can then be simplified to be able to specific a particular repo and release (which provides these).

Would also be good to allow optionally specifying a matching sha256 for verifying integrity.
