### ISSUE TITLE
list commits will only list the latest 1 commit

### ISSUE THREAD

**Issue by w-le** [PlaceOS/frontend-loader#63]
**Describe the bug**
list commits (with no count param) will only list the latest (1) commit, instead of 50 most recent commits.
The response also appears to be missing the commit's `subject`, `date` and ``author`. It has hash (`commit`) and branch `name`.

This prevents rolling back to previous versions of frontends (which is a common scenario when there is an unexpected bug in a new frontend).

**Your environment**
2205.0-rc0 on placeos-dev

**To Reproduce**
Click edit on backoffice repo on placeos-dev, see GET commits request, which is:
https://placeos-dev.aca.im/api/engine/v2/repositories/repo-Fhyon5PsoYO/commits
(no params)
which returns only a single commit ([used to return 50](https://github.com/PlaceOS/frontend-loader/blob/master/src/placeos-frontend-loader/api/repositories.cr#L20) I think)

**Expected behavior**
Return 50 most recent commits

**Screenshots**
Response to GET commits (no params)
![image](https://user-images.githubusercontent.com/10395560/166402880-8cce3ac7-31ec-49a7-bc2a-9dcdb46b4c72.png)
Request (resulting in above response)
![image](https://user-images.githubusercontent.com/10395560/166402909-fcee5e62-5650-477d-99c0-0a448b4f3a42.png)

**Comment by caspiano** [comment]
This will require a bit of work.
There have been some unnoticed breaking changes in API as the result of a recent refactor.
While performance is _excellent_ after this refactor (confirmed with the recent OpenTelemetry addition), it has also introduced some incorrectness.
The `commits` endpoint is actually returning the commit hashes for the tags and branches at the moment.

@stakach and I have come up with some plans to refactor to clone the repository without checking out the head, and see what other juice we can squeeze out of `git ls-remote`. Having a neat way to query git metadata is very valuable for `build` as well.
