### ISSUE TITLE
After pulling the latest version from backoffice, app doesn't update to the latest while backoffice has the latest commit

### ISSUE THREAD

**Issue by ksra08** [PlaceOS/frontend-loader#80]
PlaceOS 2210.4

I've pulled the latest commit from backoffice but on the app it doesn't show the same commit. 
When you ssh into the frontend-loader container, it shows that the version is what you see in browser (different to what backoffice displays

<img width="996" alt="Screen Shot 2022-11-16 at 4 57 21 pm" src="https://user-images.githubusercontent.com/78706760/202137563-9065e3f6-e672-4a8b-8ed9-c483dd654785.png">

**Comment by ksra08** [comment]
FYI @jeremyw24

**Comment by w-le** [comment]
The impact is that normal end users have no way of updating a frontend app. So Sravani is blocked from testing the latest version. That's a significant impact. The version served should always be what frontend-loader says it is.

**Comment by stakach** [comment]
I've already fixed the issue in the latest version of PlaceOS.
Please don't create issues unless you can replicate on the current release

I've also fixed the issue for @ksra08
